/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'ZPSMMsg'
 * message type.
 */

public class ZPSMMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 21;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 1;

    /** Create a new ZPSMMsg of size 21. */
    public ZPSMMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new ZPSMMsg of the given data_length. */
    public ZPSMMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ZPSMMsg with the given data_length
     * and base offset.
     */
    public ZPSMMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ZPSMMsg using the given byte array
     * as backing store.
     */
    public ZPSMMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ZPSMMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public ZPSMMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ZPSMMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public ZPSMMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ZPSMMsg embedded in the given message
     * at the given base offset.
     */
    public ZPSMMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ZPSMMsg embedded in the given message
     * at the given base offset and length.
     */
    public ZPSMMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <ZPSMMsg> \n";
      try {
        s += "  [source=0x"+Long.toHexString(get_source())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [seq=0x"+Long.toHexString(get_seq())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: source
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'source' is signed (false).
     */
    public static boolean isSigned_source() {
        return false;
    }

    /**
     * Return whether the field 'source' is an array (false).
     */
    public static boolean isArray_source() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'source'
     */
    public static int offset_source() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'source'
     */
    public static int offsetBits_source() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'source'
     */
    public short get_source() {
        return (short)getUIntBEElement(offsetBits_source(), 8);
    }

    /**
     * Set the value of the field 'source'
     */
    public void set_source(short value) {
        setUIntBEElement(offsetBits_source(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'source'
     */
    public static int size_source() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'source'
     */
    public static int sizeBits_source() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: seq
    //   Field type: int, unsigned
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'seq' is signed (false).
     */
    public static boolean isSigned_seq() {
        return false;
    }

    /**
     * Return whether the field 'seq' is an array (false).
     */
    public static boolean isArray_seq() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'seq'
     */
    public static int offset_seq() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'seq'
     */
    public static int offsetBits_seq() {
        return 8;
    }

    /**
     * Return the value (as a int) of the field 'seq'
     */
    public int get_seq() {
        return (int)getUIntBEElement(offsetBits_seq(), 16);
    }

    /**
     * Set the value of the field 'seq'
     */
    public void set_seq(int value) {
        setUIntBEElement(offsetBits_seq(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'seq'
     */
    public static int size_seq() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'seq'
     */
    public static int sizeBits_seq() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: wlist
    //   Field type: short[][], unsigned
    //   Offset (bits): 24
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'wlist' is signed (false).
     */
    public static boolean isSigned_wlist() {
        return false;
    }

    /**
     * Return whether the field 'wlist' is an array (true).
     */
    public static boolean isArray_wlist() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'wlist'
     */
    public static int offset_wlist(int index1, int index2) {
        int offset = 24;
        if (index1 < 0 || index1 >= 9) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        if (index2 < 0 || index2 >= 2) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index2 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'wlist'
     */
    public static int offsetBits_wlist(int index1, int index2) {
        int offset = 24;
        if (index1 < 0 || index1 >= 9) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        if (index2 < 0 || index2 >= 2) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index2 * 8;
        return offset;
    }

    /**
     * Return the entire array 'wlist' as a short[][]
     */
    public short[][] get_wlist() {
        short[][] tmp = new short[9][2];
        for (int index0 = 0; index0 < numElements_wlist(0); index0++) {
          for (int index1 = 0; index1 < numElements_wlist(1); index1++) {
              tmp[index0][index1] = getElement_wlist(index0,index1);
          }
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'wlist' from the given short[][]
     */
    public void set_wlist(short[][] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
          for (int index1 = 0; index1 < value[index0].length; index1++) {
              setElement_wlist(index0,index1, value[index0][index1]);
          }
        }
    }

    /**
     * Return an element (as a short) of the array 'wlist'
     */
    public short getElement_wlist(int index1, int index2) {
        return (short)getUIntBEElement(offsetBits_wlist(index1, index2), 8);
    }

    /**
     * Set an element of the array 'wlist'
     */
    public void setElement_wlist(int index1, int index2, short value) {
        setUIntBEElement(offsetBits_wlist(index1, index2), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'wlist'
     */
    public static int totalSize_wlist() {
        return (144 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'wlist'
     */
    public static int totalSizeBits_wlist() {
        return 144;
    }

    /**
     * Return the size, in bytes, of each element of the array 'wlist'
     */
    public static int elementSize_wlist() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'wlist'
     */
    public static int elementSizeBits_wlist() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'wlist'
     */
    public static int numDimensions_wlist() {
        return 2;
    }

    /**
     * Return the number of elements in the array 'wlist'
     * for the given dimension.
     */
    public static int numElements_wlist(int dimension) {
      int array_dims[] = { 9, 2,  };
        if (dimension < 0 || dimension >= 2) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
